name: release

on:
  workflow_dispatch:

jobs:
  bump_version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/bump-package@v2.1.2
        with:
          major-keywords: breaking
          minor-keywords: feat,minor
          patch-keywords: fix,chore,word

  build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: resorptionbidonvilles/frontend:latest,resorptionbidonvilles/frontend:${{ steps.tag.outputs.new_tag }}
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
